hal_hw_interface:  Update to ROS2 Humble APIs
`controller_manager::ControllerManager` `get_current_state()` member function renamed to `get_state()`
https://github.com/ros-controls/ros2_control/pull/512

    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp: In function ‘void reset_controller_cb()’:
    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:93:23: error: ‘using element_type = class controller_interface::ControllerInterfaceBase’ {aka ‘class controller_interface::ControllerInterfaceBase’} has no member named ‘get_current_state’
       93 |     if (controller.c->get_current_state().id() ==
          |                       ^~~~~~~~~~~~~~~~~

`rclcpp::InitOptions`:  `shutdown_on_siginc` member variable renamed
to `shutdown_on_signal`
https://github.com/ros2/rclcpp/pull/1771

    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp: In function ‘int rtapi_app_main()’:
    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:136:13: error: ‘class rclcpp::InitOptions’ has no member named ‘shutdown_on_sigint’; did you mean ‘shutdown_on_signal’?
      136 |   init_opts.shutdown_on_sigint = false;
          |             ^~~~~~~~~~~~~~~~~~
          |             shutdown_on_signal

`controller_manager::ControllerManager`:
`read()`/`update()`/`write()` member function signatures changed to
require time and period args
https://github.com/ros-controls/ros2_control/pull/715

    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp: In function ‘void funct(void*, int64_t)’:
    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:230:55: error: cannot convert ‘int64_t’ {aka ‘long int’} to ‘const rclcpp::Duration&’
      230 |   CONTROLLER_MANAGER->read(CONTROLLER_MANAGER->now(), period);
          |                                                       ^~~~~~
          |                                                       |
          |                                                       int64_t {aka long int}
    In file included from [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:37:
    /opt/ros/humble/include/controller_manager/controller_manager.hpp:155:65: note:   initializing argument 2 of ‘void controller_manager::ControllerManager::read(const rclcpp::Time&, const rclcpp::Duration&)’
      155 |   void read(const rclcpp::Time & time, const rclcpp::Duration & period);
          |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:235:57: error: cannot convert ‘int64_t’ {aka ‘long int’} to ‘const rclcpp::Duration&’
      235 |   CONTROLLER_MANAGER->update(CONTROLLER_MANAGER->now(), period);
          |                                                         ^~~~~~
          |                                                         |
          |                                                         int64_t {aka long int}
    In file included from [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:37:
    /opt/ros/humble/include/controller_manager/controller_manager.hpp:167:57: note:   initializing argument 2 of ‘controller_interface::return_type controller_manager::ControllerManager::update(const rclcpp::Time&, const rclcpp::Duration&)’
      167 |     const rclcpp::Time & time, const rclcpp::Duration & period);
          |                                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
    [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:241:56: error: cannot convert ‘int64_t’ {aka ‘long int’} to ‘const rclcpp::Duration&’
      241 |   CONTROLLER_MANAGER->write(CONTROLLER_MANAGER->now(), period);
          |                                                        ^~~~~~
          |                                                        |
          |                                                        int64_t {aka long int}
    In file included from [...]/hal_ros_control/hal_hw_interface/src/hal_control_node.cpp:37:
    /opt/ros/humble/include/controller_manager/controller_manager.hpp:178:66: note:   initializing argument 2 of ‘void controller_manager::ControllerManager::write(const rclcpp::Time&, const rclcpp::Duration&)’
      178 |   void write(const rclcpp::Time & time, const rclcpp::Duration & period);
          |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~